version: '3.8'

services:
  pasterbin-mysql:
    image: mysql:5.7.32
    container_name: pasterbin-mysql
    restart: unless-stopped
    tty: true
    environment:
      # with mysql
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: pasterbin-mysql
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - app-network

  pasterbin:
    container_name: pasterbin
    build: 
      context: .
      dockerfile: Dockerfile
    image: pasterbin
    restart: unless-stopped
    tty: true
    ports:
      - 8080:8080
      - 8000:8000
    volumes:
      - ./:/var/www
    depends_on:
      - pasterbin-mysql
    env_file:
      - .env
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
