version: '3.8'

services:

  db:
    image: mysql:5.7.32
    container_name: mysqldb5.7.32
    environment:
      # with mysql
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      external_network:
        aliases:
          - mysqldb5.7.32

  app:
    container_name: pasterbin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html/pasterbin
    depends_on:
      - db

networks:
  external_network:

