version: '3.8'

services:
  db:
    image: mysql:5.7.32
    container_name: mysqldb5.7.32
    restart: unless-stopped
    environment:
      # with mysql
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - app_network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app_network

  pasterbin:
    container_name: pasterbin
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve'
    restart: unless-stopped
    ports:
      - 8000:85
    volumes:
      - .:/pasterbin
      - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app_network

volumes:
  dbdata:
    driver: local

networks:
  app_network:
    driver: bridge
