version: '3.8'

services:

  database:
    image: mysql:5.7
    container_name: database
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306

    expose:
      # Opens port 3306 on the container
      - 3306

    volumes:
      - my-db:/var/lib/mysql

  app:
    container_name: pasterbin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html/pasterbin
    depends_on:
      - database

volumes:
  my-db:

