version: '3.8'

services:
  pasterbin-mysql:
    image: mysql:5.7.32
    container_name: pasterbin-mysql
    restart: unless-stopped
    tty: true
    environment:
      # with mysql
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: pasterbin-mysql
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - app-network

  pasterbin:
    container_name: pasterbin
    build:
      context: ./
      dockerfile: Dockerfile
    command: 'composer install && php artisan migrate'
    image: laravel8-php-fpm-80
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - 8080:86
    volumes:
      - ./:/var/www
    depends_on:
      - pasterbin-mysql
    env_file:
      - .env
    networks:
      - app-network
  
  nginx:
    image: nginx:1.19.8-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
